resource_group_name       = "replace-me-rg"
location                  = "replace-me-location"
key_vault_name            = "replace-me-kv"
key_vault_resource_group  = "replace-me-rg"
secret_name               = "replace-me-secret"