name: Deploy Vendor Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Package version, for example 1.0.0"
        required: true
        type: string
        default: "1.0.0"

      environment:
        description: "Deployment environment"
        required: true
        type: choice
        options:
          - test
          - prod

permissions:
  id-token: write
  contents: read
  actions: write

env:
  STORAGE_ACCOUNT_NAME: stgridfozzentest
  CONTAINER_NAME: vendor-package

jobs:
  prepare-package:
    name: Prepare vendor package
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download package
        shell: bash
        run: |
          set -euo pipefail

          az storage blob download \
            --account-name "$STORAGE_ACCOUNT_NAME" \
            --container-name "$CONTAINER_NAME" \
            --name "${{ inputs.version }}.zip" \
            --file package.zip \
            --auth-mode login

      - name: Extract package
        shell: bash
        run: |
          set -euo pipefail

          rm -rf vendor-package
          mkdir -p vendor-package

          unzip -q package.zip -d vendor-package

          echo "Downloaded package contents:"
          find vendor-package -maxdepth 3 -type f -print

- name: Replace vendor tfvars
  shell: bash
  run: |
    rm -f package/terraform/ka.tfvars

    cp \
      terraform/environments/${{ inputs.environment }}/vendor/ka.tfvars \
      package/terraform/ka.tfvars


      - name: Upload prepared package
        uses: actions/upload-artifact@v4
        with:
          name: vendor-package
          path: package/
          if-no-files-found: error
          retention-days: 1

  deploy:
    name: Deploy vendor package
    needs: prepare-package

    uses: Lomobuu/TFBiS/.github/workflows/terraform.yaml@513b3bd0bbd27ae118d96aa371e4f2f136cda0c3

    with:
      environment: ${{ inputs.environment }}
      working_directory: package/terraform
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      backend_config: ../../terraform/backend-configs/backend-vendor-package-${{ inputs.environment }}.tfbackend
      var_file: ka.tfvars

    secrets: inherit

    permissions:
      actions: write
      contents: read
      id-token: write