name: Destroy Core Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to destroy
        required: true
        type: choice
        options:
          - test
          - prod

permissions:
  contents: read
  id-token: write

env:
  # Configure Terraform to run in automation.
  TF_IN_AUTOMATION: true

  # OIDC Azure Connection
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  destroy:
    runs-on: ubuntu-24.04

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}

      - name: Terraform Init
        working-directory: terraform/environments/${{ inputs.environment }}/core
        run: |
          terraform init \
            -backend-config=../../../backend-configs/backend-${{ inputs.environment }}.tfbackend

      - name: Terraform Destroy
        working-directory: terraform/environments/${{ inputs.environment }}/core
        run: |
          terraform destroy -auto-approve