name: Deploy Core Infrastructure

permissions: {}

on:
  pull_request:
    branches: [main]
    paths:
      - terraform/environments/*/core/**
      - terraform/modules/core/**

  workflow_dispatch: {}

jobs:
  deploy-test:
    name: Deploy test
    uses: Lomobuu/TFBiS.github/workflows/terraform.yaml
    with:
      environment: test
      working_directory: terraform/environments/test/core
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      backend_config: ../../../backend-configs/backend-test.tfbackend
    secrets: inherit
    permissions:
      actions: write
      contents: read
      id-token: write

  deploy-prod:
    name: Deploy prod
    uses: Lomobuu/TFBiS/.github/workflows/terraform.yaml
    with:
      environment: prod
      working_directory: terraform/environments/prod/core
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      backend_config: ../../../backend-configs/backend-prod.tfbackend
    secrets: inherit
    permissions:
      actions: write
      contents: read
      id-token: write